# Generated by Django 4.1.7 on 2023-02-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('connection_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('profile_picture', models.CharField(max_length=150, null=True)),
                ('profile_bio', models.CharField(max_length=150, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_logout', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatDb.connections')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatDb.user')),
            ],
        ),
        migrations.AddField(
            model_name='connections',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='chatDb.user'),
        ),
        migrations.AddField(
            model_name='connections',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='chatDb.user'),
        ),
    ]
