# Generated by Django 4.1.7 on 2023-03-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatDb', '0003_alter_connections_connection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
