# Generated by Django 4.1.7 on 2023-03-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatDb', '0005_delete_dummy_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='--', upload_to='static/images'),
        ),
    ]
