# Generated by Django 4.1.7 on 2023-03-12 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatDb', '0009_alter_dummy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Dummy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofilepic',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='chatDb.user'),
        ),
    ]
