# Generated by Django 4.1.7 on 2023-03-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatDb', '0010_userprofilepic_delete_dummy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='profile_picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
